### ISSUE TITLE
delete collections

### ISSUE THREAD

**Issue by jmue** [alexbakker/webdav-provider#12]
Deleting collections does currently not work because Uri is missing a trailing slash in that case. I'm unsure whether it would be better to add the trailing slash in the deleteDocument method or fix the file path within the filemeta cache entries. I tend towards the latter.

**Comment by alexbakker** [comment]
Thanks for the report, I hadn't encountered this yet myself. Turns out the WebDAV specification says that clients SHOULD add a trailing slash to the URL for collections. So we should do this for any other actions on collections as well.

> or fix the file path within the filemeta cache entries. I tend towards the latter.

Agreed. I think I'll expose a separate property for this, as the Path type discards trailing slashes.
