### ISSUE TITLE
Please publish it to f-droid.org

### ISSUE THREAD

**Issue by Agagamand** [alexbakker/webdav-provider#24]
F-Droid is an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform

**Comment by boognish-rising** [comment]
Everyone knows what F-droid is, though I do agree this app would be right at home hosted there. More to the point, though, did you happen to see the issue 2 down from yours (issue #22)? I'm not asking to be a jerk about this issue essentially being a duplicate, but rather because it contains within it what I believe you seek. No, not an F-droid hosted instance of Webdav-Provider, but an APK file so you don't necessarily need to build it using Android Studio or whatever other means. I can confirm that the linked APK files work and are free of any funny stuff as of, IDK... a month or so ago but I'd be willing to wager that they'll always be "Funny stuff-free" and should remain working so long as Webdav-Provider does (so, until Google breaks it and/or abandons SAF or the use of document providers or some such, effectively doing the same thing). Having gone both routes, i.e., the easy way and the somewhat less convenient one, I can confirm that the latter is really not difficult. That said, the end result is the same ¯\_(ツ)_/¯

**Comment by alexbakker** [comment]
I currently don't have plans to publish the app on F-Droid, but it is available on the Google Play Store now: https://play.google.com/store/apps/details?id=dev.rocli.android.webdav

**Comment by yurtpage** [comment]
@alexbakker I can create a publishing metadata and then it will be automatically build and published for each new release without your involvement. But the F-Droid requires your consent to publish your app.
So could you allow to do that? The WebDAV is one of the missing parts to build an independent self-hosted ecosystem and your app may play a significant role in this

**Comment by alexbakker** [comment]
@yurtpage I appreciate it, but this app is going to be Google Play Store only for now.
